# Taps
tap 'buo/cask-upgrade'

# Binaries
brew 'ack'
brew 'bash'
brew 'bash-completion@2'
brew 'bat'
brew 'docker'
brew 'eza'
brew 'findutils'
brew 'fd'
brew 'fzf'
brew 'gawk'
brew 'git'
brew 'git-extras'
brew 'git-delta'
brew 'git-flow'
brew 'git-lfs'
brew 'gnu-sed'
brew 'grep'
brew 'hub'
brew 'oh-my-posh'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'nvim'
brew 'openssh'
brew 'p7zip'
brew 'parallel'
brew 'pigz'
brew 'pv'
brew 'screen'
brew 'ssh-copy-id'
brew 'thefuck'
brew 'tlrc'
brew 'tree'
brew 'wget'
brew 'zopfli'
brew 'zsh'
brew 'zsh-completions'
brew 'zoxide'


# Apps
cask 'angry-ip-scanner'
cask 'drawio'
cask 'firefox@developer-edition'
cask 'kitty'
#cask 'logitech-g-hub'
cask 'obsidian'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'webex'
cask 'zoom'

# Fonts
cask 'font-hack-nerd-font'
cask 'font-meslo-lg-nerd-font'

# Mac App Store
#mas 'Serial', id: 877615577

