# chezmoi external downloads
# Direct binary downloads for tools that aren't easily available via package managers
# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# SECURITY NOTE: The checksums below are examples and MUST be updated with real values
# To get real checksums, download the files and run: shasum -a 256 <file>
# For production use, always verify checksums from official sources

# Only download if we're on a supported platform and the tool isn't already installed
{{- $os := .chezmoi.os -}}
{{- $arch := .chezmoi.arch -}}

# age encryption tool (if not available via package manager)
{{- if and (or (eq $os "linux") (eq $os "darwin")) (not (lookPath "age")) }}
".local/bin/age":
  type: "archive"
  url: "https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-{{ $os }}-{{ $arch }}.tar.gz"
  stripComponents: 1
  include: ["age"]
  executable: true
{{- if eq $os "darwin" }}
{{- if eq $arch "amd64" }}
  checksum:
    sha256: "2156e7e7a7c1c95ff7a8f5bdaf7b0a25c9b1982d4c8f8e3e7c75e1e2a3b4c5d6"
{{- else if eq $arch "arm64" }}
  checksum:
    sha256: "3267f8f8b8d2d96gg8b9g5cebe8c1a36d0c2093e5d9g9f4f8d86f2f3b4c5d6e7"
{{- end }}
{{- else if eq $os "linux" }}
{{- if eq $arch "amd64" }}
  checksum:
    sha256: "4378g9g9c9e3e07hh9c0h6dfcf9c2b47e1d3104f6e0h0g5g9e97g3g4c5d6e7f8"
{{- else if eq $arch "arm64" }}
  checksum:
    sha256: "5489h0h0d0f4f18ii0d1i7eged0d3c58f2e4215g7f1i1h6h0f08h4h5d6e7f8g9"
{{- end }}
{{- end }}
{{- end }}

# chezmoi itself (for bootstrapping on systems without package managers)
{{- if not (lookPath "chezmoi") }}
".local/bin/chezmoi":
  type: "file" 
  url: "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-{{ $os }}-{{ $arch }}"
  executable: true
  # Note: Latest release checksums change frequently, consider pinning specific version
  # For production use, replace 'latest' with specific version and add checksums
{{- end }}

# fzf (as fallback if not available)
{{- if and (or (eq $os "linux") (eq $os "darwin")) (not (lookPath "fzf")) }}
".local/bin/fzf":
  type: "archive"
  url: "https://github.com/junegunn/fzf/releases/download/v0.64.0/fzf-0.64.0-{{ $os }}_{{ $arch }}.tar.gz"
  executable: true
{{- if eq $os "darwin" }}
{{- if eq $arch "amd64" }}
  checksum:
    sha256: "1e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j"
{{- else if eq $arch "arm64" }}
  checksum:
    sha256: "2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3k"
{{- end }}
{{- else if eq $os "linux" }}
{{- if eq $arch "amd64" }}
  checksum:
    sha256: "3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3k4l"
{{- else if eq $arch "arm64" }}
  checksum:
    sha256: "4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8f9g0h1i2j3k4l5m"
{{- end }}
{{- end }}
{{- end }}

# shellcheck (shell script linter) - if not available via package manager
{{- if and (eq $os "linux") (not (lookPath "shellcheck")) }}
".local/bin/shellcheck":
  type: "archive"
  url: "https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.{{ $os }}.{{ $arch }}.tar.xz"
  stripComponents: 1
  include: ["shellcheck-v0.9.0/shellcheck"]
  executable: true
{{- if eq $arch "x86_64" }}
  checksum:
    sha256: "700324c6dd0ebea0117591c6cc9d7350d9c7c5c287acbad7630fa17b1d4d9e2f"
{{- else if eq $arch "aarch64" }}
  checksum:
    sha256: "179c579ef3481317d130adebede74a34dbbc2df961a70916dd4039ebf0735fae"
{{- end }}
{{- end }}

# Include platform-specific externals
{{- if eq $os "windows" }}
# Windows-specific tools that aren't available via winget/scoop
{{- end }}

{{- if eq $os "darwin" }}
# macOS-specific tools that might not be in Homebrew
{{- end }}

{{- if eq $os "linux" }}
# Linux-specific tools
{{- end }}