languages:
  nodejs: latest
  python: latest
  golang: latest
  rust: latest
cli_tools:
  eza:
    cargo: eza
    brew: eza
    apt: eza
    description: Modern ls replacement with colors and icons
  fd:
    cargo: fd-find
    brew: fd
    apt: fd-find
    dnf: fd-find
    pacman: fd
    scoop: fd
    description: Modern find replacement
  ripgrep:
    cargo: ripgrep
    brew: ripgrep
    apt: ripgrep
    dnf: ripgrep
    pacman: ripgrep
    scoop: ripgrep
    description: Fast grep replacement
  bat:
    cargo: bat
    brew: bat
    apt: bat
    dnf: bat
    pacman: bat
    scoop: bat
    description: Cat with syntax highlighting
  zoxide:
    cargo: zoxide
    brew: zoxide
    apt: zoxide
    dnf: zoxide
    pacman: zoxide
    description: Smart cd replacement with frecency
  sheldon:
    cargo: sheldon
    brew: sheldon
    description: Fast zsh plugin manager
  git-delta:
    cargo: git-delta
    brew: git-delta
    apt: git-delta
    dnf: git-delta
    scoop: delta
    description: Better git diff viewer
  lazygit:
    brew: lazygit
    apt: lazygit
    scoop: lazygit
    description: Terminal UI for git
  jq:
    brew: jq
    apt: jq
    dnf: jq
    pacman: jq
    scoop: jq
    description: JSON processor
  yq:
    brew: yq
    go: github.com/mikefarah/yq/v4@latest
    description: YAML processor
  tldr:
    cargo: tealdeer
    npm: tldr
    brew: tlrc
    apt: tldr
    description: Simplified man pages
  fzf:
    brew: fzf
    apt: fzf
    dnf: fzf
    pacman: fzf
    go: github.com/junegunn/fzf@latest
    description: Fuzzy finder for command line
platform_packages:
  darwin:
    system:
      - btop
      - curl
      - mackup
      - openssh
      - p7zip
      - parallel
      - pigz
      - pv
      - screen
      - ssh-copy-id
      - thefuck
      - trash
      - tree
      - wget
      - zopfli
      - gh
      - shellcheck
    development:
      - docker
      - git
      - git-extras
      - git-flow
      - git-lfs
      - hub
      - neovim
      - node
      - tmux
    shell:
      - bash
      - bash-completion@2
      - findutils
      - gawk
      - gnu-sed
      - grep
      - oh-my-posh
      - zsh
      - zsh-completions
    applications:
      - angry-ip-scanner
      - bazecor
      - betterdisplay
      - discord
      - drawio
      - firefox@developer-edition
      - kitty
      - obsidian
      - sublime-text
      - visual-studio-code
      - webex
      - zoom
      - slack
    fonts:
      - font-hack-nerd-font
      - font-meslo-lg-nerd-font
  linux:
    debian:
      essential:
        - build-essential
        - curl
        - wget
        - git
        - zsh
        - tmux
        - neovim
        - tree
        - unzip
        - software-properties-common
        - ca-certificates
        - gnupg
        - lsb-release
        - apt-transport-https
    fedora:
      essential:
        - gcc
        - gcc-c++
        - curl
        - wget
        - git
        - zsh
        - tmux
        - neovim
        - tree
        - unzip
        - dnf-plugins-core
        - ca-certificates
    arch:
      essential:
        - base-devel
        - curl
        - wget
        - git
        - zsh
        - tmux
        - neovim
        - tree
        - unzip
        - ca-certificates
  windows:
    winget:
      - Git.Git
      - Neovim.Neovim
      - Microsoft.WindowsTerminal
      - JanDeDobbeleer.OhMyPosh
      - Kitty.Kitty
      - Docker.DockerDesktop
      - Mozilla.Firefox.DeveloperEdition
      - Obsidian.Obsidian
      - Microsoft.VisualStudioCode
    scoop:
      - git
      - neovim
      - fzf
      - ripgrep
      - fd
      - bat
      - delta
      - jq
      - curl
      - wget
      - oh-my-posh
package_manager_priority:
  - mise
  - cargo
  - brew
  - apt
  - dnf
  - pacman
  - winget
  - scoop
  - npm
  - pip
  - go
