alias sshconfig="vim $HOME/.ssh/config"
alias vimconfig="vim $DOTFILES/vim/.vimrc"
alias zshconfig="vim $XDG_CONFIG_HOME/zsh/.zshrc"
alias dotconfig="vim $DOTFILES"
alias zsource="source $XDG_CONFIG_HOME/zsh/.zshrc" 
alias vim="nvim"
alias docker-images-update="docker images | grep -v REPOSITORY | awk '{print $1}' | xargs -L1 docker pull"
alias eza="eza --long --icons --no-quotes --all --group-directories-first --octal-permissions --no-user --git"
alias ll="eza"
alias cd="z"
alias gwctl="~/.gwctl/gwctl --config=$GWCTL_CONFIG"

alias gst="git status"
alias gp="git pull"
alias gd="git diff"
